[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "test_anvil_local"
version = "0.1.0"
description = "Test Anvil Local"

[tool.setuptools]

[tool.setuptools.packages.find]
include = [
  "server_code"
]
